export const categories = ['Poems','Articles','Book reviews','Song reviews','Movie reviews','Daily practices'];
export type Post = {id:string;title:string;category:string;excerpt:string;body:string;tags:string;image:string;date:string;status:string;sample?:boolean;likes?:number;liked?:boolean};
export const defaults={title:'Safar-e-Rachna',subtitle:'A journey through words, wonder & everything in between.',author:'Gourav Dutta',bio:'A student of technology, a wanderer in words. I write to notice the things we rush past — in books, in cinema, in life.',headline:'Some journeys begin with a single word.',banner:'/landscape.jpg',photo:'',tagline:'Writer · Student · Curious observer',instagram:'',linkedin:'',twitter:'',github:'',substack:'',website:'',labels:categories.join(','),theme:'parchment'};
export const samples:Post[]=[
{id:'sample-1',title:'The art of paying attention',category:'Articles',excerpt:'Perhaps the world has not grown quieter. Perhaps we have forgotten how to listen.',body:'The late afternoon enters a room without asking permission. It rests on the edge of a book, on the chipped lip of a cup, on all the things we have stopped seeing.\n\nAttention is a small act of return. When we look closely at something ordinary, it begins to resist the word ordinary. A street becomes a collection of lives. A familiar voice carries a hesitation we had missed.\n\nWriting begins here: with the willingness to stay a little longer. Before the argument, before the beautiful sentence, there is the patient work of noticing.\n\nWhat did you walk past today that might deserve a second look?',tags:'attention,life,reflection',image:'/landscape.jpg',date:'2026-09-24',status:'published',sample:true},
{id:'sample-2',title:'Where the light stays',category:'Poems',excerpt:'A poem for the small things that refuse to leave us.',body:'There is a light\nthat does not belong to the sun.\n\nIt lives in a cup\nyou left beside the window,\nin the page you folded\nto find your way home.\n\nEvening comes.\nThe room forgets its colours.\n\nStill, some things\nkeep their own dawn.',tags:'light,memory,home',image:'',date:'2026-09-23',status:'published',sample:true},
{id:'sample-3',title:'A room, a book, a world beyond',category:'Book reviews',excerpt:'On reading slowly, and letting a book change the questions you ask.',body:'A reading notebook\n\nA useful review begins with a specific encounter. Which passage made you pause? What did the book make possible that its summary could not?\n\nRather than announcing that a book is good or bad, begin with its choices: the voice, the distance between narrator and character, the things left unsaid. Then ask what those choices cost.\n\nThis sample is a starting point for your own review. Add the book title, author, passages you want to discuss, and your considered response.',tags:'books,reading,literature',image:'/scholar.jpg',date:'2026-09-22',status:'published',sample:true},
{id:'sample-4',title:'The silence between the notes',category:'Song reviews',excerpt:'Sometimes the part of a song that stays with us is the space it leaves.',body:'A listening notebook\n\nListen once for the voice. Listen again for everything beneath it. Where does the arrangement step back? Where does a repeated line acquire a different meaning?\n\nThe strongest music writing joins close listening to a personal response. A feeling is a beginning; a precise description helps another listener discover why it happened.\n\nReplace this sample with your review, including the song, artist, and the moments worth returning to.',tags:'music,sound,art',image:'',date:'2026-09-21',status:'published',sample:true},
{id:'sample-5',title:'What the camera leaves behind',category:'Movie reviews',excerpt:'An invitation to look beyond the plot and into the frame.',body:'A cinema notebook\n\nA film tells us where to look. It also tells us how long to keep looking. A doorway, an empty chair, a face held in silence: each can carry a story before anyone speaks.\n\nWhen reviewing a film, choose one scene and describe its work. Consider framing, sound, performance, and the cut that ends it. How does the form shape the feeling?\n\nUse this sample as a place to begin your own review. Name the film and director, and flag spoilers before discussing the ending.',tags:'cinema,art,stories',image:'',date:'2026-09-20',status:'published',sample:true},
{id:'sample-6',title:'Who decides which stories survive?',category:'Daily practices',excerpt:'A question at the intersection of literature, power, and memory.',body:'Practice notebook\n\nWhich stories reach us, and which disappear before they can be heard? Start with a particular time and place, then examine the institutions that publish, translate, preserve, and teach literature.\n\nResearch three distinct mechanisms: political restrictions, commercial incentives, and the availability of translation. Find a documented example for each. Avoid assuming that one mechanism explains every absence.\n\nA good essay makes its uncertainties visible. What evidence would change your conclusion?',tags:'history,politics,literature',image:'',date:'2026-09-19',status:'published',sample:true}
];
export const prompts=[
['Science & evidence','How do we know the Apollo Moon landings happened?','Compare independent tracking, lunar samples, and retroreflector experiments. What makes evidence independently verifiable?'],
['Literature & power','Who gets published when politics decides what can be said?','Compare censorship, market pressures, and translation in two specific countries or periods. Distinguish documented cases from inference.'],
['History & art','Who paid for the Renaissance, and what did they get in return?','Trace one patron and one artist. Explore how money, religion, and civic prestige shaped the work.'],
['Technology & society','Can an algorithm expand our taste, or only repeat it?','Examine recommendation feedback loops and discovery. Propose a measurable definition of cultural diversity.'],
['Language & identity','What does a poem lose — and gain — in translation?','Compare two translations of one poem. Look at rhythm, cultural references, and the translator’s choices.'],
['Ecology & cities','Who owns the shade in a growing city?','Investigate tree cover, heat, public space, and inequality using a specific city as your case study.'],
['Philosophy & memory','Is forgetting a failure, or part of how we make meaning?','Separate everyday forgetting from clinical conditions. Contrast one philosophical argument with cognitive research.'],
['Cinema & ethics','Can a beautiful film ask us to admire a terrible person?','Examine how framing, music, and narrative sympathy affect judgment in one film. Include an alternative reading.'],
['Economics & culture','Why do some languages have so few books in translation?','Investigate publishing economics, grants, readership, and gatekeepers. Ground the essay in one language.'],
['Music & history','When does a protest song become part of the establishment?','Follow one song across its original context, commercial use, and later reinterpretations.'],
['Space & society','Who should get to name places beyond Earth?','Explore scientific conventions, cultural representation, and the difference between naming and ownership.'],
['Books & technology','Did the printing press democratise knowledge equally?','Compare access, literacy, language, and censorship. Choose a period and avoid treating Europe as the whole world.']
];
