import {getChatGPTUser} from '../../chatgpt-auth';
import {db} from '@/lib/db';
import {socialFields,socialUrl,themes} from '@/lib/profile';
import {defaults,samples,categories,Post} from '@/lib/content';
export const dynamic='force-dynamic';
export async function GET(){try{const user=await getChatGPTUser(),d=db();let config=await d.prepare('SELECT * FROM settings WHERE id=1').first<{owner:string;data:string}>();if(!config&&user){await d.prepare('INSERT OR IGNORE INTO settings(id,owner,data) VALUES(1,?,?)').bind(user.userId,JSON.stringify(defaults)).run();config=await d.prepare('SELECT * FROM settings WHERE id=1').first<{owner:string;data:string}>();}const owner=!!user&&config?.owner===user.userId;const {results}=await d.prepare('SELECT * FROM posts ORDER BY date DESC').all();const all=[...results,...samples.filter(p=>!results.some(r=>r.id===p.id))].filter(p=>p.status!=='deleted'&&(owner||p.status==='published'));const likes=await d.prepare('SELECT post,COUNT(*) AS count FROM likes GROUP BY post').all();const mine=user?(await d.prepare('SELECT post FROM likes WHERE user=?').bind(user.userId).all()).results:[];return Response.json({posts:all.map(p=>({...p,likes:likes.results.find(l=>l.post===p.id)?.count||0,liked:mine.some(l=>l.post===p.id)})),settings:config?{...defaults,...JSON.parse(config.data)}:defaults,owner,user:user?{name:user.displayName}:null});}catch(e){console.error(e);return Response.json({error:'The journal could not be loaded. Please try again.'},{status:503});}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request origin'},{status:403});const u=await getChatGPTUser();if(!u)return Response.json({error:'Sign in to continue.'},{status:401});const d=db(),b=await req.json() as {action:string;data?:Record<string,string>;post?:Post;id?:string;liked?:boolean;body?:string;name?:string},config=await d.prepare('SELECT * FROM settings WHERE id=1').first<{owner:string;data:string}>();const owner=config?.owner===u.userId;
if(['save','settings','delete'].includes(b.action)&&!owner)return Response.json({error:'Only the author can edit this journal.'},{status:403});
if(b.action==='settings'){const data={...defaults,...(config?JSON.parse(config.data):{})};for(const key of Object.keys(defaults)){const v=b.data?.[key];if(v===undefined)continue;if(typeof v!=='string'||v.length>3000)return Response.json({error:'Please keep profile fields under 3,000 characters.'},{status:400});(data as Record<string,string>)[key]=v;}for(const [key,label] of socialFields){const url=socialUrl(data[key]);if(url===null)return Response.json({error:'Enter a valid website URL for '+label},{status:400});data[key]=url;}if(!themes.some(t=>t[0]===data.theme))return Response.json({error:'Choose an available theme.'},{status:400});await d.prepare('UPDATE settings SET data=? WHERE id=1').bind(JSON.stringify(data)).run();}
else if(b.action==='save'){const p=b.post;if(!p||typeof p.title!=='string'||!p.title.trim()||typeof p.body!=='string'||!p.body.trim()||p.title.length>220||p.body.length>120000) return Response.json({error:'Add a title and body (title up to 220 characters).'}, {status:400});if(!['draft','published'].includes(p.status)||!categories.includes(p.category))throw new Error('Invalid post');const id=typeof p.id==='string'?p.id:crypto.randomUUID();await d.prepare('INSERT INTO posts(id,title,category,excerpt,body,tags,image,date,status) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,category=excluded.category,excerpt=excluded.excerpt,body=excluded.body,tags=excluded.tags,image=excluded.image,status=excluded.status').bind(id,p.title,p.category,String(p.excerpt||p.body.slice(0,150)),p.body,String(p.tags||'').slice(0,500),String(p.image||'').slice(0,3000),p.date||new Date().toISOString(),p.status).run();return Response.json({ok:true,id});}
else if(b.action==='delete'){await d.prepare('INSERT INTO posts(id,title,category,excerpt,body,tags,image,date,status) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status').bind(b.id,'','','','','','',new Date().toISOString(),'deleted').run();}
else if(['like','comment'].includes(b.action)){const p=await d.prepare('SELECT status FROM posts WHERE id=?').bind(b.id).first<{status:string}>();if(p?p.status!=='published':!samples.some(p=>p.id===b.id))return Response.json({error:'Post not found'},{status:404});if(b.action==='like'){if(b.liked)await d.prepare('INSERT OR IGNORE INTO likes(post,user) VALUES(?,?)').bind(b.id,u.userId).run();else await d.prepare('DELETE FROM likes WHERE post=? AND user=?').bind(b.id,u.userId).run();}else{if(typeof b.body!=='string'||!b.body.trim()||b.body.length>3000)return Response.json({error:'Write a comment of 1–3,000 characters.'},{status:400});await d.prepare('INSERT INTO comments(id,post,user,name,body,date) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),b.id,u.userId,String(b.name||'Reader').slice(0,80),b.body.trim(),new Date().toISOString()).run();}}
else return Response.json({error:'Unknown action'},{status:400});return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:'Could not save. Your writing is still here; please try again.'},{status:503});}}
